path:
  PDFs_PATH: "./data/PDFs"
  PROCESSED_PATH: "./data/processed"
  DATABASE_PATH: "./db" 

token:
  chunk_size: 1000
  chunk_overlap: 200

retriever:
  k: 4

OpenAI:
  temperature: 1.0
  max_tokens: 100
  model: "gpt-3.5-turbo"

chatReceipe:
  limit: 3